### ISSUE TITLE
             I want to contribute to your project regarding command line section. Can you please tell me what is to be written in this section and in what languages should the files be added?

### ISSUE THREAD

**Issue by Arjunhg** [vivekpal1/masterlinux#5]

**Comment by vivekpal1** [comment]
Hey @Arjunhg 

[masterlinux](https://github.com/vivekpal1/masterlinux) is created using [mdBook](https://github.com/rust-lang/mdBook).
I would suggest reading [its docs](https://rust-lang.github.io/mdBook) if you want to contribute to the structure and backend of the book.

If you want to contribute to just Docs, [Go through the src directory containing markdown files](https://github.com/vivekpal1/masterlinux/tree/main/src).
Markdown prior knowledge is required.
